language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  - JOB=doc
  - JOB=gpu
  - JOB=cpu

compiler:
  - gcc
services:
  - docker
install:
  - sudo apt-get install nvidia-cuda-toolkit
script:
  - cd docker
  - echo ${JOB}
#  - bash anakin_docker_build_and_run.sh -p NVIDIA-GPU -o Ubuntu -m Build
#branches:
#  only:
#  - master
#  - developing
#notifications:
#  email:
#    recipients:
#    - xukailu@baidu.com
#    on_success: change
#    on_failure: always
