language: cpp
services:
  - docker
os:
  - linux
  
before_install:
  - sudo apt-get install nvidia-cuda-toolkit
script:
  - cd docker
  - ls
  - nvcc --version
 # - chmod +x ./anakin_docker_build_and_run.sh 
 # - ./anakin_docker_build_and_run.sh  -p NVIDIA-GPU -o Ubuntu -m Build
